name: HungerWarps
version: 1.0
main: com.zp4rker.hwarps.HungerWarps
description: A warping plugin that costs hunger levels
commands:
  setwarp:
    usage: /setwarp <name>
    aliases: [sw, swarp]
  delwarp:
    usage: /delwarp <name>
    aliases: [dw, dwarp]
  warp:
    aliases: [w]